spring.application.name=FlowOS
jwt.secret = ${JWT_SECRET:replace-this-with-a-real-secret-set-as-env-variable}
spring.datasource.url=jdbc:postgresql://localhost:5432/flow-db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:replace-this-with-a-real-password-set-as-env-variable}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

google.client.id = ${GOOGLE_CLIENT_ID:replace this with a valid google client id }

spring.data.redis.host=localhost
spring.data.redis.port=6379

security.jwt.expiration = 1000 * 60 * 15